intermediate phase
Haba1234/hw-test pull request #11
Opened 2021-03-03 17:44 UTC by Haba1234

## Домашнее задание №9 «Валидатор структур»

### Критерии оценки
- [ ] Пайплайн зелёный - 3 балла
- [ ] Добавлены юнит-тесты - до 4 баллов
- [ ] Понятность и чистота кода - до 3 баллов

#### Зачёт от 7 баллов

2021-03-18 08:44 UTC, balabanovds requested changes
Спасибо за работу.
Есть замечания.

2021-03-18 08:44 UTC, balabanovds commented on hw09_struct_validator/validator.go
> +			errStr += fmt.Sprintf("Field: %s: %s\n", err.Field, err.Err)
может лучше использовать strings.Builder?

2021-03-18 08:44 UTC, balabanovds commented on hw09_struct_validator/validator.go
> +		return errValid
то есть возвращаете пустой слайс?

2021-03-18 08:44 UTC, balabanovds commented on hw09_struct_validator/validator.go
>  	return nil
то есть если повесили на строку валидатор 'max' то это не ошибка?

2021-03-18 08:44 UTC, balabanovds commented on hw09_struct_validator/validator.go
> +		valKey, err := strconv.Atoi(regexp.MustCompile(`([0-9]+)`).FindString(key))
regex.MustCompile вызывается каждый раз при вызове функции, а это довольно тяжелая операция..
хорошо бы все MustCompile как-то вынести, чтобы они компилировались один раз

2021-03-18 08:44 UTC, balabanovds commented on hw09_struct_validator/validator.go
> +	return errValid
если не было ошибок, то все равно возвращается ошибка, а не nil

2021-03-18 08:44 UTC, balabanovds commented on hw09_struct_validator/validator.go
> +		for _, key := range strings.Split(keys, "|") {
а если повесили на Int не валидную конфигурацию - например `min:20|max:10`?

2021-03-18 08:44 UTC, balabanovds commented on hw09_struct_validator/validator_test.go
> +			expectedErr: ValidationErrors{},
nil же

2021-03-18 16:15 UTC, Haba1234 commented on hw09_struct_validator/validator.go
> +			errStr += fmt.Sprintf("Field: %s: %s\n", err.Field, err.Err)
Согласен, для ускорения можно

2021-03-18 16:26 UTC, Haba1234 commented on hw09_struct_validator/validator.go
> +		return errValid
в принципе да :) он или пустой или с ошибками
Или тут более корректно все таки nil возвращать?

2021-03-18 16:32 UTC, Haba1234 commented on hw09_struct_validator/validator.go
>  	return nil
согласен, если прилетел не Int, то просто nil возвращался

2021-03-18 16:33 UTC, Haba1234 commented on hw09_struct_validator/validator.go
> +	return errValid
выше было :) поправил на nil

2021-03-18 16:35 UTC, Haba1234 commented on hw09_struct_validator/validator_test.go
> +			expectedErr: ValidationErrors{},
да, это все было взаимосвязано начиная с возврата вместо нил пустой структуры. Все пофиксил

2021-03-18 16:48 UTC, Haba1234 commented on hw09_struct_validator/validator.go
> +		for _, key := range strings.Split(keys, "|") {
тут даже не знаю... если возраст допустим не будет удовлетворять min или max, будет ошибка. Но при этом нет проверки условия что минимум обязательно должен быть больше максимума

2021-03-18 17:08 UTC, Haba1234 commented on hw09_struct_validator/validator.go
> +		valKey, err := strconv.Atoi(regexp.MustCompile(`([0-9]+)`).FindString(key))
Вынес в структуру, возможно есть более правильные варианты?

2021-03-19 02:39 UTC, balabanovds commented on hw09_struct_validator/validator.go
> +		valKey, err := strconv.Atoi(regexp.MustCompile(`([0-9]+)`).FindString(key))
регексы будут теперь компилиться каждый вызов функции
можно сделать так чтобы они компилились еще реже - вынести в глобальную видимость пакета

2021-03-19 02:40 UTC, balabanovds commented on hw09_struct_validator/validator.go
>  	return nil
а Вы точно везде проверили?

2021-03-19 02:41 UTC, balabanovds commented on hw09_struct_validator/validator.go
> +		return errValid
если не структура, то надо конкретную ошибку возвращать, а не пустой слайс

2021-03-19 02:46 UTC, balabanovds commented on hw09_struct_validator/validator.go
> +		for _, key := range strings.Split(keys, "|") {
там можно сделать проверку. но это по желанию. 
основной посыл - нужно думать о крайних и нестандартных случаях и закрывать возможные дыры

2021-03-19 02:49 UTC, balabanovds requested changes
Уже лучше, но остались еще замечания

2021-03-19 11:06 UTC, Haba1234 commented on hw09_struct_validator/validator.go
> +		valKey, err := strconv.Atoi(regexp.MustCompile(`([0-9]+)`).FindString(key))
Вынес

2021-03-19 11:09 UTC, Haba1234 commented on hw09_struct_validator/validator.go
> +		for _, key := range strings.Split(keys, "|") {
Если смотреть в общем, проверки это само собой. Стараюсь их делать, где не забываю :)
в этом конкретном случае я бы не стал делать проверку, т.к. по условиям у нас возможны варианты ключа:
1. min
2. max
3. min или max. Причем условие "или", было бы "и", проверка требовалась бы однозначно.

2021-03-19 11:30 UTC, Haba1234 commented on hw09_struct_validator/validator.go
> +		return errValid
выполнено

2021-03-24 07:19 UTC, balabanovds approved these changes

2021-04-07 13:55 UTC, merged