HW02 is completed
Haba1234/hw-test pull request #2
Opened 2020-12-09 16:38 UTC by Haba1234

2020-12-11 05:26 UTC, Antonboom requested changes
Здравствуйте!

Предлагаю заменить IsPunct на `== '/'` и должно быть похоже на правду.
Предварительно
6 / 10

P.S. Не забывайте пользоваться шаблонами Pull Request'ов

2020-12-11 05:26 UTC, Antonboom commented on hw02_unpack_string/unpack.go
> +var resultStr strings.Builder // готовим построитель для новой строки
такие вещи крайне редко выносятся на уровень пакета

2020-12-11 05:26 UTC, Antonboom commented on hw02_unpack_string/unpack.go
> +func checkSymbols(char rune) bool { //nolint:gofmt
можно переписать в виде
```go
func ... {
    return expression
}
```

2020-12-11 05:26 UTC, Antonboom commented on hw02_unpack_string/unpack_test.go
> +			expected: "",
а почему здесь не 
```
....df
```
?

2020-12-11 05:26 UTC, Antonboom commented on hw02_unpack_string/unpack.go
> +	if !unicode.IsLetter(char) && !unicode.IsDigit(char) && unicode.IsPunct(char) && (char != 92) {
исходя из каких требований появилось `unicode.IsPunct`?

2020-12-11 05:26 UTC, Antonboom commented on hw02_unpack_string/unpack.go
> +	if !unicode.IsLetter(char) && !unicode.IsDigit(char) && unicode.IsPunct(char) && (char != 92) {
92 - magic number

2020-12-11 05:26 UTC, Antonboom commented on hw02_unpack_string/unpack.go
> +		if index == 0 && (unicode.IsDigit(char) || unicode.IsPunct(char)) {
в IsPunct явно входит не только слэш

2020-12-11 15:43 UTC, Haba1234 commented on hw02_unpack_string/unpack.go
> +func checkSymbols(char rune) bool { //nolint:gofmt
done

2020-12-11 15:43 UTC, Haba1234 commented on hw02_unpack_string/unpack.go
> +var resultStr strings.Builder // готовим построитель для новой строки
понял о чем речь, передал чуток

2020-12-11 15:44 UTC, Haba1234 commented on hw02_unpack_string/unpack.go
> +	if !unicode.IsLetter(char) && !unicode.IsDigit(char) && unicode.IsPunct(char) && (char != 92) {
done

2020-12-11 15:48 UTC, Haba1234 commented on hw02_unpack_string/unpack_test.go
> +			expected: "",
понял задание как отсеивание всего, кроме букв, цифр и \
Соответственно точка, тем более в начале строки = ошибка

2020-12-11 15:53 UTC, Haba1234 commented on hw02_unpack_string/unpack.go
> +	if !unicode.IsLetter(char) && !unicode.IsDigit(char) && unicode.IsPunct(char) && (char != 92) {
была мысль сделать по универсальнее, т.е. проверка на символ, цифру и символы пунктуации, куда входит в том числе \. Но итоговую проверку на недопустимые символы пока ограничил только символом \, не хватило времени интереснее сделать

2020-12-11 15:57 UTC, Haba1234 commented on hw02_unpack_string/unpack.go
> +		if index == 0 && (unicode.IsDigit(char) || unicode.IsPunct(char)) {
ответ выше, в этой проверке уже разрешенные символы (из пунктуации прошел дальше только "слеш") и идет проверка что из себя представляет первый символ

2020-12-15 08:10 UTC, Antonboom approved these changes
Принято
10 / 10

2020-12-15 08:10 UTC, Antonboom commented on hw02_unpack_string/unpack.go
> +func checkSymbols(char rune) bool { //nolint:gofmt
я имел в виду функцию checkSymbols :)

2020-12-15 15:13 UTC, merged