HW05 is complited!
Haba1234/hw-test pull request #5
Opened 2021-02-04 17:23 UTC by Haba1234

## Домашнее задание №5 «Параллельное исполнение»

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены новые юнит-тесты - до 4 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2021-02-04 20:12 UTC, kulti requested changes
Роман, спасибо за выполнение ДЗ.

Если что-то непонятно или никак не получается сделать, то всегда можно спросить. Можно в личке в слаке, можно в общем чате. Кто-нибудь из преподавателей или студентов обязательно поможет :)

Сейчас отключен тест из шаблона ДЗ. Нужно его включить и исправить решение.

2021-02-04 20:12 UTC, kulti commented on hw05_parallel_execution/run.go
> +	// Возврат ошибки, если кол-во задач с ошибками >= m.
Слишком много комментариев. Они по большей части дублируют код и загрязняют его. Главная проблема комментариев в том, что они редко чем помогают и начинаю мешать, когда правки в коде приведут к их устареванию (а это происходит очень быстро). Рекомендую придерживаться правила — «не комментировать очевидное, а если код неочевидный, сделать его очевидным».

2021-02-04 20:12 UTC, kulti commented on hw05_parallel_execution/run.go
> +	for currentTask < len(tasks) {
Очень странный цикл из-за ручного управления счетчитком цикла. К тому же счетчик инициализируется очень далеко от начала цикла.

Как минимум, это можно написать компактнее и понятнее:
```
for currentTask := 0; currentTask < len(tasks); currentTask++
```

Но я бы заменил счетчик цикла на стандартное имя i, т.к. других счетчиков тут нет, нет смысла использовать сложные имена.
```
for i := 0; i < len(tasks); i++
```

А еще лучше сделать вообще вот так:
```
for _, task := range tasks
```
Самый компактный и легко читаемый вариант.

2021-02-04 20:12 UTC, kulti commented on hw05_parallel_execution/run.go
> +		chNumTask <- currentTask // Новая задача.
Зачем передавать порядковый номер, если можно передать таск? С индексом всегда есть возможность «отстрелить себе ногу».

2021-02-04 20:12 UTC, kulti commented on hw05_parallel_execution/run.go
> +		if err := <-chErr; true {
Очень странная конструкция. Не понимаю, что этот код пытается выразить.

Вот тоже самое, но без if'a
```
err := <-chErr
if err != nil {
...
```

2021-02-04 20:12 UTC, kulti commented on hw05_parallel_execution/run_test.go
> +		t.Skip()
Верните, пожалуйста, старый тест. Решение этого ДЗ должно его проходить. Иначе оно не будет принято.

PS. Подозреваю дело в том, что тест падает с ошибкой «tasks were run sequentially?». Если не получится найти проблему, то напишите мне в слаке — я подскажу.

2021-02-05 05:04 UTC, Haba1234 commented on hw05_parallel_execution/run.go
> +		if err := <-chErr; true {
если честно, я тоже :))) вот что значит писать код перед сном

2021-02-05 05:05 UTC, Haba1234 commented on hw05_parallel_execution/run.go
> +		chNumTask <- currentTask // Новая задача.
еще не привык к каналам. Отличное замечание! Переделал

2021-02-05 05:06 UTC, Haba1234 commented on hw05_parallel_execution/run.go
> +	for currentTask < len(tasks) {
Спасибо, переписал код. Нет предела совершенству, но я только учусь :)

2021-02-05 05:06 UTC, Haba1234 commented on hw05_parallel_execution/run.go
> +	// Возврат ошибки, если кол-во задач с ошибками >= m.
Принято :)
я пока больше себе пишу

2021-02-05 07:34 UTC, kulti commented on hw05_parallel_execution/run.go
> +	// Возврат ошибки, если кол-во задач с ошибками >= m.
Ок. Главное, чтобы это не переросло в привычку :)

2021-02-05 15:55 UTC, Haba1234 commented on hw05_parallel_execution/run_test.go
> +		t.Skip()
Забыл убрать, вернул. Сначала не падало с такой ошибкой, потом после экспериментов с новыми тестами оказалось что стало падать .
Так что продолжил эксперименты с каналами и горутинами.
Вышло, что вышло. Может подскажешь какие-то более красивые варианты решения.
И у меня так и не вышло на 100% проходить сотню тестов при использовании буферизированных каналов. Первый тест с ошибками иногда проваливался, т.к. один из воркеров успевал еще одну задачу выполнить (результат n + m + 1).

2021-02-06 07:41 UTC, kulti requested changes
Решение получается очень сложное и запутанное. Думаю, пришло время начать сначала :)

Совет такой — подумать о настоящей задаче. Часто мы увлекаемся деталями решения и начинаем думать «как бы мне в этот канал с ошибками так писать, чтобы что-то там». И понеслась :)

В этом ДЗ истинные задачи такие:
1. Выполнять работу в N горутинах.
2. Дожидаться остановки всех горути.
3. Прекращать работу, если ошибок >= M.

Первая задача наполовину решена идеально — цикл из трех строк с запуском воркеров. Сам воркер переусложнен (видимо, увлеклись какой-то побочной идеей).

Вторая задача состоит из двух частей. Дожидание сделано с помощью WaitGroup — самое лучшее и логичное решение. А вот для остановки добавлен еще один канал stop. Можно ли тут обойтись одним каналом chTask? 

Предлагаю тут остановится и переписать все внутри одной функции Run. Не надо думать о третьей задаче, решаем только первые две. Выделять новые функции, типы, пакеты и прочее тоже не нужно — это задача рефакторинга. Сначала надо написать «портянку» кода, которая будет задачу решать.

После этого должна получится функция Run которая проходит один из двух изначальных тестов. Ориентировочный размер функции 20-30 строк (зависит от того, как пустые строчки расставлять). Думаю, у вас это легко получится.

Зафиксируйте этот результат. Если хорошо владеете гитом, то им, если нет, то сделайте копию файлов, чтобы не потерять достигнутый результат.

Потом останется подумать, как считать ошибки и останавливать работу. И опять же истинные задачи такие:
1. Считать количество ошибок.
2. Прекратить выполнять новые задачи.

Решений масса. Вы уже попробовали считать количество ошибок с помощью каналов. Еще можно их считать с помощью переменной. Главное не забывать, что настоящая задача «считать», а не «считать с помощью». Т.е. всегда можно попробовать другой подход, если получается как-то сложно.

Прекратить выполнять новые задачи. Что это значит? Что задачи больше не передают воркерам, или воркеры сами их не берут в работу? Опять же есть варианты.

Для решения, когда задачи больше не дают воркерам, а ошибки считают в переменной могу дать ориентир, что размер Run увеличится еще строчек на 10. Для остальных вариантов точно не знаю. С каналом чуть побольше должно быть, вроде.

И еще одну подсказку дам. Никаких горутин, кроме воркеров, запускать не нужно.

2021-02-06 07:41 UTC, kulti commented on hw05_parallel_execution/run_test.go
> +		t.Skip()
Написал :)

2021-02-07 15:26 UTC, Haba1234 commented
Переосмыслил на свежую голову и переписал код.
Заодно посмотрел лекцию про синхронизацию 2, можно было бы заюзать atomic или sync.cond :)

2021-02-07 20:18 UTC, kulti requested changes
Решен стало немножко лучше, но пока еще делает немного не то.

Есть ли у вас промежуточный вариант, где нет проверки ошибок? Хочется понять, проблемы в решении появляются сразу или уже после того, как начинаете добавлять проверку ошибок.

Рекомендую сделать проверку числа ошибок с атомиком — будет намного проще. С каналом все не так очевидно. Возможно, именно из него и появились эти навороченные проверки?

sync.Cond в этом ДЗ не нужен (этот примитив синхронизации в принципе довольно редко, когда нужен).

2021-02-07 20:18 UTC, kulti commented on hw05_parallel_execution/run.go
> +//nolint:gocognit
Согласен с линтером. Слишком много условий и if'oв.

Проще, чем в первый, раз, но все равно запутанная логика.

2021-02-07 20:18 UTC, kulti commented on hw05_parallel_execution/run.go
> +	var chTask = make(chan Task, 1) // Канал для выдачи задач.
Не уловил из дальнейшего кода, зачем буфер для этого канала?

2021-02-07 20:18 UTC, kulti commented on hw05_parallel_execution/run.go
> +	for (countTasksOK + countTasksErr) < len(tasks) {
Рекомендую не писать такие циклы. 

Ручное управление выходом из цикла — это слишком сложно для понимания. Иногда, конечно, без этого трудно обойтись, но это очень-очень редкая ситуация.

Помимо сложности у этого цикла есть другая проблема — он будет «жрать» CPU. Дело в том, что он часто будет работать вхолостую. Пока воркер не вернет ответ, этот цикла будет постоянно делать бесполезные проверки и идти на новую итерацию, повторяя те же самые проверки.

Выглядит так, что вы упустили истинную задачу — перестать выполнять задачи при достижении m ошибок. Судя по решение, вы выбрали вариант перестать давать эти задачи. Самое простое, что для этого можно сделать — это выйти из цикла.

2021-02-08 07:15 UTC, Haba1234 commented on hw05_parallel_execution/run.go
> +	for (countTasksOK + countTasksErr) < len(tasks) {
Думаю, что получилось и без атомика.
Не до конца осознавал как работают каналы и как правильно их готовить, чтобы избегать дедлоков и зависания.

2021-02-08 08:58 UTC, kulti approved these changes, later dismissed
В итоге получилось здорово. Код довольно легко читается. ДЗ принято - 10/10.

Рекомендую посмотреть разбор этого ДЗ, в нем решение с атомиком. Сможете сравнить. https://youtu.be/lD7q5S3BVto

2021-02-08 08:58 UTC, kulti commented on hw05_parallel_execution/run_test.go
> +		t.Skip()
Этот тест нужно либо удалить, либо включить его.

2021-02-08 11:03 UTC, Haba1234 commented on hw05_parallel_execution/run_test.go
> +		t.Skip()
Включил

2021-02-08 11:04 UTC, kulti approved these changes

2021-02-28 13:59 UTC, merged